app/routes/chatbot.py
from flask import (
    render_template,
    request,
    jsonify,
    session,
    send_from_directory,
    Blueprint,
)

import os
from ..utils import get_bot_response, init_bot_config, validate_email
from .. import db
from ..models import Leads


bp = Blueprint("chatbot", __name__)


@bp.route("/chatbot-iframe")
@bp.route("/chatbot/iframe")
def iframe():
    return render_template("chatbot.html")


@bp.route("/preview")
def preview():
    return render_template("preview.html")


@bp.route("/chatbot/css")
def send_css():
    return send_from_directory("static" + os.sep + "css", "output.css")


@bp.route("/embed")
def embed_chatbot():
    return send_from_directory("static" + os.sep + "js", "embed.js")


@bp.route("/chatbot/init-bot", methods=["POST"])
def init_bot():
    bot_id = request.args.get("id")
    session["bot_id"] = bot_id
    bot_config_result = init_bot_config(bot_id)

    return jsonify(bot_config_result), bot_config_result["status"]


@bp.route("/chatbot/message", methods=["POST"])
def bot():
    data = request.json
    user_input = data.get("message")
    bot_id = data.get("botId")
    response = get_bot_response(bot_id, user_input)

    return jsonify({"status": 200, "response": str(response)})


@bp.route("/chatbot/email-submit", methods=["POST"])
def email_submit():
    data = request.json
    email = data.get("email")

    if validate_email(email):
        lead = Leads(
            bot_id=data.get("botId"),
            email=email,
        )
        db.session.add(lead)
        db.session.commit()

        return jsonify({"status": 200})

    else:
        return jsonify({"status": 400, "error": "INVALID_EMAIL"}), 400

app/templates/chatbot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatbot</title>

    <link href="{{ url_for('chatbot.send_css') }}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

</head>

<body class="bg-transparent">
    <div class="flex flex-col h-[100vh] w-[100vw] rounded-xl border bg-white">
        <div class="border-b pl-4 pr-4 pt-2 pb-1 flex justify-between items-center">
            <div class="flex flex-row items-center">
                <img id="header-pfp" class="rounded-full w-7 h-7 mr-3 drop-shadow-2xl" src="" />
                <h3 class="font-[600] text-lg bot-title"></h3>
            </div>

            <div>
                <button id="close-button" class="m-2 bg-white">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                        <path fill="#212121"
                            d="M2.39705176,2.55378835 L2.46966991,2.46966991 C2.73593648,2.20340335 3.15260016,2.1791973 3.44621165,2.39705176 L3.53033009,2.46966991 L8,6.939 L12.4696699,2.46966991 C12.7625631,2.1767767 13.2374369,2.1767767 13.5303301,2.46966991 C13.8232233,2.76256313 13.8232233,3.23743687 13.5303301,3.53033009 L9.061,8 L13.5303301,12.4696699 C13.7965966,12.7359365 13.8208027,13.1526002 13.6029482,13.4462117 L13.5303301,13.5303301 C13.2640635,13.7965966 12.8473998,13.8208027 12.5537883,13.6029482 L12.4696699,13.5303301 L8,9.061 L3.53033009,13.5303301 C3.23743687,13.8232233 2.76256313,13.8232233 2.46966991,13.5303301 C2.1767767,13.2374369 2.1767767,12.7625631 2.46966991,12.4696699 L6.939,8 L2.46966991,3.53033009 C2.20340335,3.26406352 2.1791973,2.84739984 2.39705176,2.55378835 L2.46966991,2.46966991 L2.39705176,2.55378835 Z">
                        </path>
                    </svg>
                </button>
            </div>
        </div>

        <div id="init-loader"
            class="bg-white rounded-xl border w-[100vw] h-[100vh] absolute top-0 left-0 z-[999] flex flex-col justify-center items-center overflow-hidden">
        </div>

        <div id="chatbox" class="bg-white my-4 overflow-y-auto h-[100%] m-4">
            <!-- Chat messages will appear here -->
        </div>

        <div class="border rounded-md flex flex-row items-center m-4">
            <input id="message-input" class="w-full outline-none px-2 disabled:bg-white peer" type="text" disabled
                autocomplete="off" placeholder="Type your message here...">

            <button id="send-button" class="m-2 bg-white peer-disabled:opacity-20">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="none" d="M0 0h24v24H0V0z"></path>
                    <path fill="#0074f0" class="color000000 svgShape"
                        d="M3.4 20.4l17.45-7.48c.81-.35.81-1.49 0-1.84L3.4 3.6c-.66-.29-1.39.2-1.39.91L2 9.12c0 .5.37.93.87.99L17 12 2.87 13.88c-.5.07-.87.5-.87 1l.01 4.61c0 .71.73 1.2 1.39.91z">
                    </path>
                </svg>
            </button>
        </div>
    </div>

    <script>
        const chatbox = document.getElementById('chatbox');
        const messageInput = document.getElementById('message-input');
        const sendButton = document.getElementById('send-button');
        const closeButton = document.getElementById('close-button');
        const initLoader = document.getElementById("init-loader");
        const headerPfp = document.getElementById("header-pfp");

        let emailMsgAdded = false;
        let shouldCaptureEmail = false;


        const loader = `
            <div class="w-full gap-x-2 flex justify-center items-center chatbot-loader">
                <div class="w-3 h-3 bg-[#d991c2] animate-pulse rounded-full"></div>
                <div class="w-3 h-3 animate-pulse bg-[#9869b8] rounded-full"></div>
                <div class="w-3 h-3 animate-pulse bg-[#6756cc] rounded-full"></div>
            </div>
        `;

        const loaderMsg = `
            <div class="container flex justify-start" id="loader">
                <div class="p-3 py-4 bg-gray-200 my-2 rounded-tl-xl rounded-tr-xl rounded-br-xl max-w-[90%]">
                    ${loader}
                </div>
            </div>
        `;

        const emailSubmitMsg = `
            <div id="email-submit-message" class="container flex justify-start">
                <div class="p-3 bg-gray-200 my-2 rounded-tl-xl rounded-tr-xl rounded-br-xl max-w-[90%]">
                    <p>To provide you with the best assistance and keep you updated with any follow-ups, could you
                        please share your email address?</p>

                    <div class="bg-white rounded-md flex flex-row items-center mt-4">
                        <input id="email-input" class="w-full outline-none px-2" type="text" autocomplete="off"
                            placeholder="Type your email here...">

                        <button id="email-send-button" class="m-2 bg-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="none" d="M0 0h24v24H0V0z"></path>
                                <path fill="#0074f0" class="color000000 svgShape"
                                    d="M3.4 20.4l17.45-7.48c.81-.35.81-1.49 0-1.84L3.4 3.6c-.66-.29-1.39.2-1.39.91L2 9.12c0 .5.37.93.87.99L17 12 2.87 13.88c-.5.07-.87.5-.87 1l.01 4.61c0 .71.73 1.2 1.39.91z">
                                </path>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        `



        function scrollToBottom() {
            document.getElementById("chatbox").lastElementChild.scrollIntoView({
                behavior: "smooth",
                block: "end"
            });
        }


        function convertToLinks(text) {
            const emailPattern = /([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/g;
            const urlPattern = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;

            text = text.replace(emailPattern, '<a style="color: #0074f0" href="mailto:$1" target="_blank">$1</a>');
            text = text.replace(urlPattern, '<a style="color: #0074f0" href="$1" target="_blank">$1</a>');

            return text;
        }


        function addBotMsg(m) {
            chatbox.insertAdjacentHTML('beforeend', `
                <div class="container flex justify-start">
                    <div class="p-3 bg-gray-200 my-2 rounded-tl-xl rounded-tr-xl rounded-br-xl max-w-[90%]">
                        <p>${m}</p>
                    </div>
                </div>
            `);
        }


        async function submitMsg() {
            let userMessage = messageInput.value;
            if (userMessage.trim() !== "") {
                chatbox.insertAdjacentHTML('beforeend', `
                    <div class="container flex justify-end">
                        <div class="p-3 bg-[#0074f0] text-white my-2 rounded-tl-xl rounded-tr-xl rounded-bl-xl max-w-[90%] mr-2">
                            <p>${userMessage}</p>
                        </div>
                    </div>
                `);
                chatbox.insertAdjacentHTML('beforeend', loaderMsg);

                messageInput.value = '';
                messageInput.disabled = true;
                scrollToBottom();

                let response = await fetch('/chatbot/message', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        message: userMessage,
                        botId: botId
                    })
                });
                let data = await response.json();
                let botMessage = data.response;

                document.getElementById("loader").remove();
                addBotMsg(convertToLinks(botMessage));

                messageInput.disabled = false;
                messageInput.focus();
                scrollToBottom();

                if (emailMsgAdded === false && shouldCaptureEmail == true) {
                    addEmailMsg();
                    emailMsgAdded = true;
                }
            }
        }


        function validateEmail(email) {
            var re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return re.test(email);
        }


        function addEmailMsg() {
            chatbox.insertAdjacentHTML('beforeend', emailSubmitMsg);

            scrollToBottom();

            setTimeout(() => {
                document.getElementById("email-send-button").addEventListener('click', submitEmail);

                let emailInput = document.getElementById("email-input");
                emailInput.focus();
                emailInput.addEventListener("keyup", (event) => {
                    if (event.key === "Enter") submitEmail();
                })
            }, 500);
        }


        async function submitEmail() {
            let userEmail = document.getElementById('email-input').value;
            if (userEmail.trim() !== "") {
                if (validateEmail(userEmail)) {
                    document.getElementById("email-submit-message").remove();
                    chatbox.insertAdjacentHTML('beforeend', loaderMsg);

                    let response = await fetch('/chatbot/email-submit', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            email: userEmail,
                            botId: botId
                        })
                    });
                    let data = await response.json();
                    document.getElementById("loader").remove();

                    if (data.status === 200) {
                        addBotMsg("Thank you for providing your email! We'll be in touch soon.")
                    } else {
                        document.getElementById("email-submit-message").remove();
                        addBotMsg("Invalid email. Please enter a valid email address.")
                        addEmailMsg();
                    }
                    scrollToBottom();

                } else {
                    document.getElementById("email-submit-message").remove();
                    addBotMsg("Invalid email. Please enter a valid email address.")
                    addEmailMsg();
                }
            }
        }


        function displayError(msg) {
            document.getElementsByClassName("chatbot-loader")[0].remove();
            initLoader.innerHTML = `
                <p class="text-3xl font-bold text-red-500 mb-4">Error</p>
                <p class="">${msg}</p>
            `;
        }


        initLoader.insertAdjacentHTML('beforeend', loader);
        const botId = new URLSearchParams(window.location.search).get("id");

        fetch(`/chatbot/init-bot?id=${botId}`, {
                method: "POST"
            })
            .then(e => {
                if (e.ok) return e.json();
                return e.text().then(r => {
                    throw new Error(r)
                })
            })
            .then(e => {

                for (let i of document.getElementsByClassName("bot-title")) i.textContent = e.bot_name;

                addBotMsg(e.welcome_message.replaceAll("\n", "<br><br>"));
                shouldCaptureEmail = e.email_capture;

                headerPfp.src = e.pic_url;
                messageInput.disabled = false;
                messageInput.focus();
                initLoader.remove();
            })
            .catch((e) => {
                console.log(e)
                let errorCode = JSON.parse(e.message).error;
                if (errorCode === "BOT_NOT_FOUND") displayError("Bot Not Found")
                else displayError("Server Error")
            })



        closeButton.addEventListener('click', () => {
            parent.postMessage("iframe_close", '*');
        });

        sendButton.addEventListener('click', submitMsg);
        messageInput.addEventListener("keyup", (event) => {
            if (event.key === "Enter") submitMsg();
        })
    </script>
</body>

</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Dashboard</title>

  <link rel="stylesheet" href="{{url_for('static',filename='css/output.css')}}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

  <style>
    .dropdown-menu {
      display: none;
    }

    .form-save:disabled {
      background-color: #003a77;
    }
  </style>
</head>

<body class="h-[100vh] bg-[#F4F7FF]">
  <div class="py-14 lg:py-20 h-[100%]">
    <h1 class="text-center mb-20 text-4xl font-bold text-[#0074f0]">Dashboard</h1>

    <div class="w-full px-4 flex flex-col items-center">
      <div class="w-[90%] mx-auto text-center bg-white rounded-lg relative py-14 px-8 sm:px-12 md:px-[60px]">

        <div class="w-full flex justify-end mb-4">
          <a href="/dashboard/new-bot" class="bg-[#0074f0] text-white px-4 py-2 rounded active:bg-[#004fa3]">New Bot</a>
        </div>

        <div id="dropdowns-container"></div>

      </div>
    </div>
  </div>
</body>

<script>
  let data = (`{{ data | safe }}`).replaceAll("\\n", "<br>").replaceAll("\n", "<br>").replace(/\\'/g, "'");
  data = JSON.parse(data);

  const container = document.getElementById("dropdowns-container");

  const dropdownSvg = `
    <svg class="-mr-1 h-5 w-5 text-gray-400 -rotate-90" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd"
        d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
        clip-rule="evenodd" />
    </svg>
  `;

  data.forEach((item, index) => {
    // Dropdown
    const dropdown = document.createElement("div");
    dropdown.classList.add("mb-4");

    const botLink = document.createElement("a");
    botLink.classList.add("w-full", "py-2", "px-4", "border", "rounded", "flex", "flex-row", "items-center", "mb-4",
      "justify-between");
    botLink.innerHTML = `
      <p>${item.bot_name}</p>
      ${dropdownSvg}
    `;
    botLink.href = `/dashboard/edit-bot/${item.id}`;
    container.appendChild(botLink)
  });
</script>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login</title>

  <link rel="stylesheet" href="{{url_for('static',filename='css/output.css')}}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>  
  <div class="bg-[#F4F7FF] py-14 lg:py-20 h-[100vh] overflow-hidden">
    <h1 class="text-center mb-20 text-4xl font-bold text-[#0074f0]">Login</h1>

    <div class="w-full">
      <div class="flex flex-wrap -mx-4">
        <div class="w-full px-4 flex flex-col items-center">
          <div
            class="w-full sm:w-[50%] md:w-[30%] mx-auto text-center bg-white rounded-lg relative overflow-hidden py-14 px-8 sm:px-12 md:px-[60px]">

            <form id="authForm">
              <div class="mb-6">
                <input type="email" name="email" placeholder="Email" required class="form-email w-full rounded-md border border-[#E9EDF4] py-3 px-5 bg-[#FCFDFE] text-base text-body-color placeholder-[#ACB6BE] outline-none
            focus-visible:shadow-none focus:border-[#0074f0] transition" />
              </div>

              <div class="mb-6">
                <input type="password" name="password" placeholder="Password" required class="form-password w-full rounded-md border border-[#E9EDF4] py-3 px-5 bg-[#FCFDFE] text-base text-body-color placeholder-[#ACB6BE] outline-none
            focus-visible:shadow-none focus:border-[#0074f0] transition" />
              </div>

              <div class="mb-10">
                <button type="submit" class="w-full rounded-md border bordder-[#0074f0] py-3 px-5 bg-[#0074f0] active:bg-[#004fa3] text-base text-white cursor-pointer
          hover:bg-dark transition duration-300 ease-in-out">
                  Login
                </button>
              </div>
            </form>

            <p class="text-base text-[#adadad]">
              Don't have an account?
              <a href="/signup" class="text-[#0074f0] hover:underline">
                Sign Up
              </a>
            </p>

          </div>

          <div id="message" style="display: none;"
            class="bg-red-500 w-full sm:w-[50%] md:w-[30%] mt-10 rounded-lg text-center py-5 text-white">
          </div>
        </div>
      </div>
    </div>
  </div>
</body>


<script>
  const messageElement = document.getElementById('message');

  function validateEmail(email) {
    var re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  }

  function displayError(msg) {
    messageElement.textContent = msg;
    messageElement.style.display = 'block';
  }

  document.getElementById('authForm').addEventListener('submit', function (event) {
    event.preventDefault();

    const email = document.getElementsByClassName('form-email')[0].value;
    const password = document.getElementsByClassName('form-password')[0].value;

    if (!validateEmail(email)) {
      displayError("Invalid email")
      return;
    }

    fetch("/login", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          email: email,
          password: password
        })
      })
      .then(e => {
        if (e.ok) return e.json();
        return e.text().then(r => {
          throw new Error(r)
        })
      })
      .then(e => {
        window.location.href = e.redirect;
      })
      .catch(e => {
        let errorCode = JSON.parse(e.message).error;
        if (errorCode === "INVALID_PASSWORD") displayError("Invalid password")
        else if (errorCode === "USER_NOT_FOUND") displayError("Could not find user")
        else displayError("Server Error")
      });
  });
</script>

</html>

app/templates/new-bot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create a New Chatbot</title>

    <link rel="stylesheet" href="{{url_for('static',filename='css/output.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    <style>
        .dropdown-menu {
            display: none;
        }

        .form-save:disabled {
            background-color: #003a77;
        }
    </style>
</head>

<body class="h-[100vh] bg-[#F4F7FF]">
    <div class="py-14 lg:py-20 h-[100%]">
        <h1 class="text-center mb-20 text-4xl font-bold text-[#0074f0]">Create a New Chatbot</h1>

        <div class="w-full px-4 flex flex-col items-center">
            <div class="w-[90%] mx-auto text-center bg-white rounded-lg relative py-14 px-8 sm:px-12 md:px-[60px]">

                <div class="mb-4">
                    <div class="mb-2 flex flex-row items-center form-field">
                        <span label-key="bot_name" class="w-[20%] text-start form-key">Bot Name</span>
                        <input val-type="text" placeholder="Enter Bot Name"
                            class="border rounded px-2 py-1 w-[100%] form-value" type="text">
                    </div>

                    <div class="mb-2 flex flex-row items-center form-field">
                        <span label-key="email_capture" class="w-[20%] text-start form-key">Capture Email</span>
                        <div val-type="dropdown" class="w-[100%] flex justify-start form-value">
                            <div class="relative inline-block w-[10rem]">
                                <button
                                    class="w-full py-2 px-4 border rounded flex flex-row items-center justify-between"
                                    onclick="toggleDropdown(this)">
                                    <p class="dropdown-text">No</p>

                                    <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor"
                                        aria-hidden="true">
                                        <path fill-rule="evenodd"
                                            d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
                                            clip-rule="evenodd"></path>
                                    </svg>

                                </button>

                                <div
                                    class="dropdown-menu absolute left-0 mt-2 w-full bg-white border rounded shadow-lg z-10">
                                    <ul class="py-1">
                                        <li>
                                            <button class="w-full text-left px-4 py-2 hover:bg-gray-100"
                                                onclick="selectOption(this, 'Yes', 0)">Yes</button>
                                        </li>
                                        <li>
                                            <button class="w-full text-left px-4 py-2 hover:bg-gray-100"
                                                onclick="selectOption(this, 'No', 0)">No</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mb-2 flex flex-row items-center form-field">
                        <span label-key="pic_url" class="w-[20%] text-start form-key">Avatar URL</span>
                        <input val-type="text" placeholder="Enter Avatar URL"
                            class="border rounded px-2 py-1 w-[100%] form-value" type="url">
                    </div>

                    <div class="mb-2 flex flex-row items-center form-field">
                        <span label-key="welcome_message" class="w-[20%] text-start form-key">Welcome Message</span>
                        <textarea val-type="textarea" placeholder="Type a Welcome Message"
                            class="border rounded px-2 py-1 w-[100%] h-40 form-value"></textarea>
                    </div>

                    <div class="mb-2 flex flex-row items-center">
                        <span label-key="welcome_message" class="w-[20%] text-start">Knowledge Documents</span>

                        <div val-type="upload" class="rounded w-[100%]">

                            <label for="document"
                                class="flex justify-center text-center cursor-pointer bg-gray-200 active:bg-gray-300 rounded py-1">
                                Choose files
                            </label>

                            <input type="file" id="document" name="document" accept=".txt" multiple required
                                class="hidden">

                            <p id="fileInfo" class="mt-2 text-sm text-gray-600 text-left"></p>
                        </div>

                    </div>
                </div>


                <div class="w-full mt-4 flex justify-end">
                    <div>
                        <button class="bg-gray-200 text-black px-4 py-2 rounded active:bg-gray-300 mr-2 form-delete"
                            onclick="cancelBot()">Cancel</button>

                        <button class="bg-[#0074f0] text-white px-4 py-2 rounded active:bg-[#004fa3] form-save"
                            onclick="createBot()">Create Bot</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>

<script>
    function toggleDropdown(button) {
        const dropdownMenu = button.nextElementSibling;
        dropdownMenu.style.display = dropdownMenu.style.display === 'block' ? 'none' : 'block';
    }

    function selectOption(button, value, idx) {
        document.getElementsByClassName("dropdown-text")[idx].textContent = value;
        button.closest('.relative').querySelector('button').nextElementSibling.style.display = 'none';
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.dropdown-menu') && !event.target.closest('.relative')) {
            const dropdowns = document.querySelectorAll('.dropdown-menu');
            dropdowns.forEach(dropdown => {
                dropdown.style.display = 'none';
            });
        }
    }
</script>

<script>
    const documentInput = document.getElementById('document');
    const fileInfo = document.getElementById('fileInfo');

    documentInput.addEventListener('change', function () {
        const files = documentInput.files;
        if (files.length > 0) {
            const allowedExtensions = /(\.txt)$/i;
            let fileDetails = '';
            for (let file of files) {
                if (!allowedExtensions.exec(file.name)) {
                    fileDetails += `${file.name}: Invalid file type. Allowed types are .txt\n`;
                    documentInput.value = '';
                    break;
                } else {
                    fileDetails += `${file.name}<br>`;
                }
            }
            fileInfo.innerHTML = `${fileDetails}`;
        } else {
            fileInfo.innerHTML = '';
        }
    });

    function validateUrl(url) {
        var pattern = new RegExp('^(https?:\\/\\/)?' + // protocol
            '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' + // domain name
            '((\\d{1,3}\\.){3}\\d{1,3}))' + // OR ip (v4) address
            '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // port and path
            '(\\?[;&a-z\\d%_.~+=-]*)?' + // query string
            '(\\#[-a-z\\d_]*)?$', 'i'); // fragment locator
        return !!pattern.test(url);
    }

    function cancelBot() {
        window.location.href = "/dashboard";
    }

    function createBot() {
        let vals = document.querySelectorAll(".form-field");
        let fileData = new FormData();
        for (let file of documentInput.files) {
            fileData.append('files[]', file, file.name);
        }

        let botData = {};
        let abort = false;

        for (let elm of vals) {
            let key = elm.querySelector(".form-key").getAttribute("label-key");
            let valElm = elm.querySelector(".form-value");
            let value;


            if (["text", "textarea"].includes(valElm.getAttribute("val-type"))) {
                value = valElm.value.replaceAll("\n\n", "\n");
            } else {
                value = valElm.querySelector(".dropdown-text").textContent.trim() === "Yes";
            }
            botData[key] = value;

            if (key === "pic_url" && validateUrl(value) === false) {
                alert("Invalid Avatar URL");
                abort = true;
            }

        }

        fileData.append("bot_data", JSON.stringify(botData))

        if (abort === false) {
            document.querySelector(".form-save").disabled = true;

            fetch("/dashboard/new-bot/create", {
                    method: 'POST',
                    body: fileData
                }).then(e => {
                    if (e.ok) return e.json();
                    return e.text().then(r => {
                        throw new Error(r)
                    })
                })
                .then(e => {
                    if(e.status === 200) window.location.href = e.redirect
                })
                .catch(e => {
                    console.log(e)
                });
        }
    }
</script>


</html>